CREATE TABLE USER(
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR (20),
  last_name VARCHAR(30),
  password VARCHAR(50),
  email VARCHAR(50),
  bio VARCHAR(500),
  want_newsletter BOOLEAN,
  municipality ENUM ('AGDER', 'INNLANDET', 'MORE_OG_ROMSDAL', 'NORDLAND',
  'OSLO', 'ROGALAND', 'VESTFOLD_OG_TELEMARK', 'TROMS_OG_FINNMARK', 'TRONDELAG', 
  'VESTLAND', 'VIKEN'),
  user_type ENUM ('BUYER', 'SELLER')
);

CREATE TABLE BUYER(
  id BIGINT,
  animal_type ENUM ('DOG', 'CAT'),
  home_type ENUM ('APARTMENT', 'HOUSE'),
  is_previous_animal_owner BOOLEAN, 
  has_children BOOLEAN,
  FOREIGN KEY (id) REFERENCES USER(id)
);

CREATE TABLE ANIMAL(
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR (20),
  age INT(2),
  bio VARCHAR(500),
  is_chipped BOOLEAN,
  is_vaccinated BOOLEAN,
  is_sterilized BOOLEAN,
  is_child_friendly BOOLEAN,
  is_active BOOLEAN,
  is_available BOOLEAN,
  animal_size ENUM ('SMALL', 'MEDIUM', 'LARGE'),
  is_female BOOLEAN
);

CREATE TABLE CAT(
  id BIGINT,
  breed ENUM ('MAINE_COON', 'PERSER', 'HELLIG_BIRMA', 'DEVON_REX', 'NORSK_SKOGSKATT',
    'NEVA_MASQUERADE', 'RAGDOLL', 'SCOTTISH_STRAIGHT', 'SHENGO_SIDDIS', 'SIAMESER',
    'BENGAL', 'SIBIRKATT', 'SPHYNX'),
    FOREIGN KEY (id) REFERENCES ANIMAL(id)
);

CREATE TABLE DOG(
  id BIGINT,
  breed ENUM ('BORDER_COLLIE', 'YORKSHIRE_TERRIER', 'POMERANIAN', 'GOLDEN_RETRIEVER',
    'NORSK_LUNDEHUND', 'SCHAFER', 'DALMATINER', 'LABRADOR_RETRIEVER', 'GREYHOUND',
    'AMERIKANSK_PITBULLTERRIER', 'ALASKA_HUSKY', 'TIBETANSK_MASTIFF', 'WHIPPET'),
	FOREIGN KEY (id) REFERENCES ANIMAL(id)
);

CREATE TABLE MATCHES(
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  animal_id BIGINT,
  buyer_id BIGINT,
  FOREIGN KEY (animal_id) REFERENCES ANIMAL(id),
  FOREIGN KEY (buyer_id) REFERENCES BUYER(id)
);






