package com.example.demo;

public enum DogRace {
    BORDER_COLLIE,
    YORKSHIRE_TERRIER,
    POMERANIAN,
    GOLDEN_RETRIEVER,
    NORSK_LUNDEHUND,
    SCHAFER,
    DALMATINER,
    LABRADOR_RETRIEVER,
    GREYHOUND,
    AMERIKANSK_PITBULLTERRIER,
    ALASKA_HUSKY,
    TIBETANSK_MASTIFF,
    WHIPPET,

}
