package com.example.demo;

public enum DogRace {
    ALASKA_HUSKY,
    BEAGLE,
    BORDER_COLLIE,
    CHINESE_CRESTED,
    DALMATINER,
    DVERGPINCHER,
    JACK_RUSSEL,
    NORSK_ELGHUND,
    SCHAFER,
    STAFFORDSHIRE_BULL_TERRIER,
    TIBETANSK_SPANIEL,
    WHIPPET
}
