package com.example.demo;

public enum DogRace {
    BORDER_COLLIE,
    STAFFORDSHIRE_BULL_TERRIER,
    ENGELSK_SETTER,
    GOLDEN_RETRIEVER,
    NORSK_ELGHUND,
    SCHAFER,
    LABRADOR_RETRIEVER,
    GORDON_SETTER,
    COCKER_SPANIEL,
    BICHION_HAVANAIS
}
